services:
    _defaults:
        autoconfigure: true
        autowire: true

    Contao\CoreBundle\Filesystem\VirtualFilesystem:
        alias: contao.filesystem.virtual.files

    Respinar\ContaoPlyrBundle\:
        resource: ../src/
        exclude: ../src/ContaoManager/